---
name: Publish

on:
  release:
    types: [published]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@v10.0.1
      - name: Run tests
        run: uv run --extra=dev pytest -vvv --showlocals
  pypi:
    needs: [test]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@v10.0.1
      - name: Build distributions
        run: |-
          uv build --sdist --wheel --out-dir dist/
          uv run --extra=release check-wheel-contents dist/*.whl
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
