---
name: Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: true
      - uses: astral-sh/setup-uv@v9.0.0
      - name: Calculate calendar version
        uses: StephaneBour/actions-calver@master
        id: calver
        with:
          date_format: '%Y.%-m.%-d'
          release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate release notes
        env:
          RELEASE: ${{ steps.calver.outputs.release }}
        run: uv run --extra=release towncrier build --draft --version "$RELEASE" >
          release-notes.md
      - name: Update changelog
        env:
          RELEASE: ${{ steps.calver.outputs.release }}
        run: uv run --extra=release towncrier build --yes --version "$RELEASE"
      - uses: stefanzweifel/git-auto-commit-action@v7
        id: commit
        with:
          commit_message: Bump CHANGELOG
          file_pattern: CHANGELOG.rst newsfragments
          skip_dirty_check: true
      - name: Tag release
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.calver.outputs.release }}
          tag_prefix: ''
          commit_sha: ${{ steps.commit.outputs.commit_hash }}
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          makeLatest: true
          bodyFile: release-notes.md
  pypi:
    needs: release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ needs.release.outputs.tag }}
          fetch-depth: 0
          persist-credentials: false
      - uses: astral-sh/setup-uv@v9.0.0
      - name: Build distributions
        run: |-
          uv build --sdist --wheel --out-dir dist/
          uv run --extra=release check-wheel-contents dist/*.whl
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
